Restrict url to use HTTPS
Rise-Vision/widget-web-page pull request #119
Opened 2020-11-16 20:55 UTC by stulees

## Description
Ensuring a url input with HTTP protocol in the Widget Settings shows a validation error message and "Save" button is disabled. 

This functionality is additional and handled separately from the `url-field` directive internal url validation logic.

## Motivation and Context
Stop propagating the use of HTTP protocol in URLs for content. We only support HTTPS. 

## How Has This Been Tested?
Tested locally and with stage version of widget in this presentation - https://apps.risevision.com/editor/workspace/872ac494-986b-49e0-b160-5920586ff5cd?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

** Need to manually change to use a HTTP url

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
n/a

2020-11-16 20:59 UTC, stulees commented
@olegrise Please review, thanks. FYI merging this PR will not merge to master as I will have a second PR that addresses logging `presentationId` separately as discussed.

2020-11-16 21:25 UTC, olegrise requested changes

2020-11-16 21:25 UTC, olegrise commented on src/settings/ctr-web-page-settings.js
> +        return !!( url && url.startsWith( "http://" ) );
@stulees do yo think it's better to test if URL starts with "https" instead? As a test I entered "www.risevision.com". It passed the validation but failed to render in preview because widget attempted to load "http://www.risevision.com"

2020-11-16 21:30 UTC, olegrise commented on src/settings/ctr-web-page-settings.js
> +        return !!( url && url.startsWith( "http://" ) );
@stulees check this out https://github.com/Rise-Vision/widget-web-page/blob/df53a6dc521fa0c31cebee2223710dd7c353b69c/src/widget/webpage.js#L212

2020-11-16 21:53 UTC, stulees commented on src/settings/ctr-web-page-settings.js
> +        return !!( url && url.startsWith( "http://" ) );
@olegrise I definitely overlooked the Widget prefixing with `http://` if protocol missing, forgot about that, good catch! I think we should continue to allow user to input url without protocol, otherwise they're going to be forced to add the protocol all the time. There's likely a lot of presentations out there that are saved without protocol. 

So to confirm, I will update the prefix to be `https://` in the Widget to ensure we're only going to load with https. Good with you?

I also just noticed the url field setting is applying a "http://" placeholder value. I'm going to see about overriding that without touching the directive.

2020-11-16 21:55 UTC, olegrise commented on src/settings/ctr-web-page-settings.js
> +        return !!( url && url.startsWith( "http://" ) );
@stulees sounds good

2020-11-18 15:57 UTC, stulees commented
@olegrise Changes have been made, validated with same presentation from description, in legacy preview, chrome os, and shared schedule (https preview).

2020-11-18 16:04 UTC, olegrise approved these changes

2020-11-18 20:43 UTC, stulees commented
@olegrise As per our discussion, I've now made the change to force adding `https://` to the url value if the protocol is missing. I've also remove the previous change in the widget code about `https://` prefix, it will remain prefixing with `http://` if url was saved without protocol to support existing presentations.

2020-11-18 21:53 UTC, olegrise approved these changes

2020-11-18 21:57 UTC, merged